### ISSUE TITLE
On mobile, infowindows & map are displaying incorrectly

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#115]
When tapping on a housing justice action icon or emergency tenant protection geography, the UI is no longer being split correctly (50% map & 50% infowindow) and the content in the infowindow is obscured by the header. This probably has to do with the search bar CSS, but haven’t verified it. 
cc @jimboweb 

![image](https://user-images.githubusercontent.com/161748/86877408-b0fc2580-c09b-11ea-9433-f823dd46df8d.png)

—-

![image](https://user-images.githubusercontent.com/161748/86877422-b9546080-c09b-11ea-9e95-e7df13c18312.png)

**Comment by jimboweb** [comment]
Is this issue separate from #114? They seem to be the same problem. 

The reason it's happening is because of the following lines in _map.css

`@media (max-width: 640px) {
  // when the infowindow & popup are open, reduce map height
  #root.aemp-popupopen #map {
    height: 50%; //this is the reason
  }

  // Hide map layers controls on mobile for now, as they get obscured
  #root.aemp-popupopen .leaflet-control-attribution,
  .leaflet-control-layers.leaflet-control-layers-expanded.leaflet-control {
    display: none;
  }
}`


I can take that part out, will it cause the problems?

**Comment by timhitchins** [comment]
Fixed with #117
