### ISSUE TITLE
Swap out form links

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#163]
We want to swap the current three google form links on the map (US protections, global protections, and housing justice actions) with two Airtable links: "Housing Protections" (https://airtable.com/shrMi8xtGqFIXtFyy) and "Housing Justice Actions and Landlord Retaliation" (https://airtable.com/shrI5HxbTqEFbk89Y). So we wouldn't have the US form anymore at all, and just have these two.

**Comment by erinmcel** [comment]
@unixjazz  What do you think about these forms as they currently are?

**Comment by erinmcel** [comment]
Not sure if we want to say "Landlord Retaliation" on the form or not..

**Comment by unixjazz** [comment]
@erinmcel: we can substitute the links whenever you are all ready!  A few suggestions:

1. In the housing justice form question "Are you on rent strike?", there are some illegal characters that have been added (you might want to make sure they are UTF-8 before importing into Airtable, I think). "Yes, no, unsure" are replicated into 4 options. "Unsure" got duplicated due to the character in "sûres."

2. Both forms look great (the housing protections is much simpler!)

3. On the question of "retaliation," you could use a different language that could encompass retaliation as well: "have you received a notice to vacate the rental property from the landlord?" or any question of that nature would be my suggestion.

4. Before this is made final: we need to finalize the automation of the data transfer from airtable to carto. @azadag has suggestions. And I can run pn the server I manage for the Brazilian map.

**Comment by erinmcel** [comment]
Thanks @unixjazz ! 

@azadag do you happen to know how to swap out the data with a cleaned version in UTF-8 without losing new form changes? Still trying to figure that out. 

@unixjazz - in terms of retaliation, what about: "Has your landlord threatened you for your inability to pay rent?"

**Comment by erinmcel** [comment]
Also I think we can swap the links now and then continue to work on the data?
