### ISSUE TITLE
Rent strike colors

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#49]
I wonder if we really need to disaggregate between possible and definite rent strikes in terms of colors? Might it make things simpler to just have one color for all rent strikes, which would be the same color as the clusters themselves? That way we don't have orange and blue houses, along with yellow clusters?
![Screen Shot 2020-04-22 at 3 32 13 PM](https://user-images.githubusercontent.com/8007917/80040240-817f4900-84ae-11ea-9635-66d0eaf57745.png)

**Comment by timhitchins** [comment]
@erinmcel This would be a very simple fix.  We just need settle on a color.

**Comment by erinmcel** [comment]
Great! Maybe we can figure it out after figuring out the additional color that will be used for tenant protections?

**Comment by clhenrick** [comment]
+1 @erinmcel think this would be good to do.

**Comment by c-i-v-i-m** [comment]
Just noting that I'm going to try to tackle this over the next few days. Aiming for a dark grey color.

**Comment by timhitchins** [comment]
Awesome!  @CI.V:IM here is the noun project page I used:
https://thenounproject.com/search/?q=house%20strike&i=1831609  I can give
you access to our acct to download what you need.  Also here are the docs
for the leaflet marker cluster:
https://github.com/Leaflet/Leaflet.markercluster

**Comment by c-i-v-i-m** [comment]
Awesome thanks!

I might need access to the account. Do you know if that would allow me to grab an svg version? Otherwise, I can just grab the black png and change the color in Gimp (no need for the account).

Just took a few minutes to check out the code and it seems pretty simple. Basically: 

- Get the marker image, color it appropriately, remove existing marker pngs.
- Remove the definition for rentStrikeUnsureIcon.
- Remove the conditional when selecting the icon in the geoJson layer.

That's it?

Did I understand correctly that we want to add the unsure / confirmed information in the popup?

**Comment by timhitchins** [comment]
@CI.V:IM I dm'd you the noun project creds on Slack.  Regarding the rent
strike layer update, yes it should hopefully be pretty simple and the tasks
you bullet-pointed match my thinking on the process as well.  Looking back,
I probably should have just used an svg icon (which you can feel free to
do) so other contributors could just edit the color on that instead of
relying on various pngs.  Also, it was mentioned in our meeting today that,
depending on the colors that are picked for the moratorium layers, we may
need to consider changing the colors of the cluster markers themselves.
There should be details on how to adjust those in the docs, but I don't
foresee that likely being an issue for the May 1st push... and if we switch
to an svg icon the change should be super simple.

In terms of the popup, it's looking like the popup/info window will
likely be the place where any specific info goes, so my understanding is
the same on that as well.  Depending on what the data/research team comes
up with will affect the specificity of that data I believe.

**Comment by c-i-v-i-m** [comment]
So it turns out the popup already displayed the status as yes/unsure.

Otherwise, I created a PR (https://github.com/antievictionmappingproject/covid-19-map/pull/53) which addresses:
 - Updated to single svg icon. 
	 Getting SVG icons to display as svgs (rather than img tags) in order to be able to style them was a bit more complicated then expected. The Icon class displays the icons in img tags, which I thought couldn't be colored. So I tried to borrow from this unmaintained plugin: https://github.com/hiasinho/Leaflet.vector-markers to create an "SVGIcon" class but the icons weren't being displayed in the right location, and the click to open popup behavior wasn't working.
	 Then, I found that we can actually color svgs in img tags using a css filter. Unfortunately, this does not seem to be supported in IE 11. So we might want to simply host the colored svg? I like that we could now easily change colors directly in the css but we need to consider that some people might view them as black.
 - Updated the color of the cluster icon to match the rent-strike icons.
 - I added some opacity to the rent-strike icons as well. Otherwise, the color of the cluster icons doesn't really match.


Alright, let me know for the svg/filter solution. I can continue down the path of creating a custom icon class as well.

**Comment by river-honer** [comment]
This all looks nice, matching the marker colour to the icons looks nice.

**Comment by clhenrick** [comment]
implemented in #60
