### ISSUE TITLE
Break index.js in to smaller pieces

### ISSUE THREAD

**Issue by river-honer** [antievictionmappingproject/covid-19-map#73]
The large index.js file is an issue for collaboration, and we should break it up in to smaller files, imported in to index.js.

It's also important to set a reasonable scope for this. I would propose these files which group together big blocks of the index.js file:

* handleData.js - includes `handleData` and all of the `handle<jurisdiction>Layer` functions
* handleQueryParams.js - includes current `inputValues` and renames the function
* cartoURIHelpers.js - includes all carto uri helpers, optionally we can just get import the built URI from the file, not just the functions
*  constants.js - URIs for google sheets or other config at the very top of the page. not for style constants for the map tho.

For the styles, @clhenrick talked about a solution, I think we talked about returning the style callbacks. maybe we can have a layerStyles.js or have them in their own files, but I think that may be another pr, just to keep this one short and hopefully *fingers crossed* not go in to a rabbit hole.

Suggestions for structure welcome, if you have alternative ideas.

**Comment by clhenrick** [comment]
@river-honer thanks, this sounds like a good starting plan. I agree keeping a PR limited in scope for an initial module separation of the existing code is a good idea as well. We can always continue to refactor as we add new features and fix existing bugs.

One thing I've done in previous projects that have relied on Carto is to have a `queries.js` module that has all the SQL queries in it so that they're easy to see in one place. I don't think they need to be exported as functions, just as ES6 template literal constants. That way in the `handleData.js` module we could have a function that's a wrapper around `fetch()` which takes a string for the SQL query and inlines it with the Carto SQL API endpoint. But if you have an idea that you think works better feel free to explore that.

For the `constants.js` module, it sounds like it might be more semantic to name it `config.js` if it contains things like table and account names, sheet ids, etc.?

I would advocate for not letting the `handleData.js` module get too large. Maybe the existing `handleData()` function could be renamed to `main()` and stay in `index.js` for now? There's some other stuff going on in that function that isn't only data related.

We might want to add another module for the map setup as well. We could use a class, but I feel a little hesitant about extending the `L.Map` class from Leaflet as it seems it could lead to increasing the mental model significantly if it starts to grow to be more complex. Personally I would prefer to have the library separate from the instance, e.g.

```js
class Map {
  constructor() {
    this.map = new L.Map();
  }
}
```

but I think it would also be fine to keep the map related code as is for now (but still separated to another module) if it proves to be too complicated or requires too much refactoring.

Lastly I think it would be good to split up the `index.css` file as well. Maybe we can group related stuff into separate Sass partials, e.g. the map header, infowindow, etc., import them all into `index.scss` then import `index.scss` into the `index.js` file. 

I happy to help with any of this as well, I'll take a look at whatever you get done later tomorrow.

**Comment by river-honer** [comment]
Awesome, thanks for all the info to get started with, I'll run with that for now and we can catch up later 👍
